# Generated by Django 5.1.6 on 2025-09-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
